### ISSUE TITLE
Suggestion for clean termination of NWChem dft.nw jobs

### ISSUE THREAD

**Issue by gcstoianowski** [NREL/ESIFHPC3#2]
As the input file dft.nw stands, the outputs from jobs using it as input (including the reference log provided by NREL) all end in 'dft optimize failed'.  When NWChem is built using MPI, this is followed by MPI_Abort, resulting in an unclean termination.  The purpose of this issue is to formally propose the addition of the word 'ignore' to the 'task dft optimize' line in dft.nw, as suggested by Edoardo Apra in https://github.com/nwchemgit/nwchem/issues/287#issuecomment-749853307
The change proposed does not alter the expected output of jobs that include it for either timing or validation purposes.

**Comment by chchang6** [comment]
Thank you for the suggestion, I've just pushed the proposed change. We will include a notification of it in the official responses.
