### ISSUE TITLE
Unclear reporting requirements for WRF4 performance

### ISSUE THREAD

**Issue by gcstoianowski** [NREL/ESIFHPC3#3]
The performance reporting spreadsheet for WRF4 includes three reference times (Write, Compute and Total) for each processor count, and "Total" is not the sum of Write and Compute in any of the cases.  On the other hand, the provided wrf_stats script generates six different times: Comp Total. Comp Avg, Init Total, Init Avg,Write Total, and Write Avg.  It appears to me that the "Write" time in the spreadsheet corresponds to "Write Avg" from wrf_stats, whereas "Compute" in the spreadsheet corresponds to "Comp Total" from wrf_stats.  What is completely unclear is how "Total" in the spreadsheet is supposed to be computed.

Please clarify.

Gerardo Cisneros-Stoianowski

**Comment by apurkaya-nrel** [comment]
The "Write" and "Compute" times reported in the performance reporting spreadsheet refer to the "Write Total" and "Comp Total" as generated by the provided wrf_stats script for each run case. The "Total" times reported in the performance reporting spreadsheet is total time reported by the WRF run in the run output from the system. 

As an example, the reference run output for the I/O type netcdf for 60 mpi ranks and 60 cores reports "real	182m36.846s", which translates to 10956.84s, which is recorded as the "Total" times for that case. This output is the total time for that run which includes all the system overhead in starting and ending the run, so it is always more than the sum of the "Write" and "Compute" times as recorded by the wrf_stats. This time output is generated by the job submission script statement: "time srun --ntasks=60 ./wrf.exe".

**Comment by gcstoianowski** [comment]
In other words, "Total" is actually an externally-measured time, not something reported by WRF itself.

Thanks for the clarification!

**Comment by chchang6** [comment]
Closing out as resolved.
